// Accessing input fields


// <input> tags are used for user interaction. 
// You can always read/overwrite their content accessing the value property of their JavaScript reference.



let myInput = document.getElementById('firstInput')
console.log(myInput.value) // OUTPUTS THE INPUT FIELD'S VALUE



// Define event listeners in HTML

    < button onclick = "myFunc(event)" > CLICK ME</button >

// then you declare the function in JS
const myFunc = function (e) {
    alert('You clicked me')
}



// Define event listeners in JavaScript (without attaching the listener in the HTML)

    /* in HTML we define the button without an event listener */
    < button id = "alert-button" > CLICK ME</button>

        // then we take a reference to that button in JS
        let myButton = document.getElementById('alert-button')

// we can now attach the event listener to the button in two ways:

// FIRST METHOD
myButton.onclick = function (e) {
    alert('You clicked me')
}

// SECOND METHOD
myButton.addEventListener('click', function (e) {
    alert('You clicked me')
})


// The e parameter is the event object, automatically generated by the event itself; 
// it contains a lot of useful info (coordinates of the mouse, the HTML element which generated the event, characters inputted etc.).
